version: 2

sources:
  - name: airbnb
    database: AIRBNB
    schema: raw
    tables:
      - name: hosts
        identifiers: raw_hosts

      - name: listings
        identifiers: raw_listings

      - name: reviews
        identifiers: raw_reviews
        config:
          loaded_at_field: date
          freshness:
            warn_after: {count: 1, period: hour}
            # error_after: {count: 24, period: hour}